/****************************************************************************************
Author:			mcook49
Date:			2022-04-07
JIRA:			[CCDA-3234]
Description:	Brain Glutamine Metabolism in Schizophrenia

Inclusion:		
1.	Age 18-50 currently 
2.	Having at least two mentions of schizophrenia, - F20* in encounter/billing diagnoses
3.	Lookback time: since 2015, Jan 1
4.	Location: JHH and BVMC/HCGH/Sibley/Suburban but comment out for now
5.	Have active MyChart account

Exclusion:		

1.	Interpreter need=yes
2.	Patients known to be deceased in Epic.
3.	Patients who have opted out of being contacted for MyChart recruitment.  
4.	Patients who have opted out of being contacted for any reason. 
5.	Has received another recruitment email from Hopkins in the last month.  
				
****************************************************************************************/
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;

--Schizophrenia
IF OBJECT_ID(N'TEMPDB..#inc_DX_LIST') IS NULL CREATE TABLE #inc_DX_LIST (DX_ID NUMERIC)
INSERT INTO #inc_DX_LIST (DX_ID)
SELECT DX_ID FROM CLARITY..EDG_CURRENT_ICD10 WHERE CODE LIKE 'F20%'

--Get patients with at least two mentions of schizophrenia
IF OBJECT_ID(N'TEMPDB..#inc_dx') IS NOT NULL DROP TABLE #inc_dx
SELECT T.PAT_ID
INTO #inc_dx
FROM 
		(
		SELECT PAT.PAT_ID, ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE) "DX_DATE" 
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.PAT_ENC PE ON PAT.PAT_ID = PE.PAT_ID
		INNER JOIN CLARITY.DBO.PAT_ENC_DX PED ON PE.PAT_ENC_CSN_ID = PED.PAT_ENC_CSN_ID
		INNER JOIN #inc_DX_LIST ED ON PED.DX_ID = ED.DX_ID
		UNION	
		--HSP_BILLING_DX
		SELECT PAT.PAT_ID, ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE)  
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.PAT_ENC PE ON PAT.PAT_ID = PE.PAT_ID
		INNER JOIN CLARITY.DBO.HSP_ACCT_DX_LIST DXL WITH (NOLOCK) ON PE.HSP_ACCOUNT_ID = DXL.HSP_ACCOUNT_ID
		INNER JOIN #inc_DX_LIST ED ON DXL.DX_ID = ED.DX_ID
		UNION
		--HSP_ADMISSION_DX
		SELECT PAT.PAT_ID, ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE)
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.HSP_ADMIT_DIAG HAD ON HAD.PAT_ID = PAT.PAT_ID
		INNER JOIN CLARITY..PAT_ENC PE ON PE.PAT_ENC_CSN_ID = HAD.PAT_ENC_CSN_ID
		INNER JOIN #inc_DX_LIST ED ON HAD.DX_ID = ED.DX_ID
		UNION
		--ARPB DX
		SELECT  DISTINCT PAT.PAT_ID, ISNULL(AT.SERVICE_DATE,AT.POST_DATE)
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.ARPB_TRANSACTIONS AT ON AT.PATIENT_ID = PAT.PAT_ID
		INNER JOIN CLARITY.DBO.V_ARPB_CODING_DX ARPB ON ARPB.TX_ID = AT.TX_ID
		INNER JOIN #inc_DX_LIST ED ON ARPB.DX_ID = ED.DX_ID 
		) T
		WHERE T.DX_DATE >= '2015-01-01'	-- Lookback time since 2015, Jan 1
		GROUP BY T.PAT_ID
		HAVING COUNT(T.PAT_ID) > 1		-- At least 2 mentions

SELECT DISTINCT
PAT.PAT_ID	AS 'ID'
FROM
	CLARITY.DBO.PATIENT PAT
	INNER JOIN	CLARITY.dbo.PATIENT_4					pat4	on pat.pat_id = pat4.pat_id 
	INNER JOIN	CLARITY.dbo.PATIENT_MYC					mychart on mychart.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.MYC_PATIENT					myc		on myc.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.COMMUNICATION_PREFERENCES	cp		on cp.PREFERENCES_ID=pat4.PREFERENCES_ID
	INNER JOIN	CLARITY.dbo.COMM_PREFERENCES_APRV		aprv	on cp.PREFERENCES_ID=aprv.PREFERENCES_ID and cp.LINE=aprv.GROUP_LINE
		LEFT JOIN	CLARITY.dbo.PATIENT_FYI_FLAGS fyif	ON fyif.PATIENT_ID = pat.PAT_ID and fyif.PAT_FLAG_TYPE_C = '1092'
	INNER JOIN CLARITY..PAT_ENC PE ON PE.PAT_ID = PAT.PAT_ID
	INNER JOIN #inc_dx DX ON DX.PAT_ID = PAT.PAT_ID
WHERE 
(FLOOR(DATEDIFF(DD,PAT.BIRTH_DATE,GETDATE())/365.25) >= 18 
	AND FLOOR(DATEDIFF(DD,PAT.BIRTH_DATE,GETDATE())/365.25) <= 50)	--Age currently between 18 and 50
AND ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE)  >= '2015-01-01'	-- Lookback time since 2015, Jan 1
AND 	MYCHART.MYCHART_STATUS_C = '1'					-- PATIENTS WITH AN ACTIVE MYCHART ACCOUNT (DEFINED AS HAVING A LOG IN WITHIN THE LAST YEAR – BASED ON EXTRACT DATE)
AND		ISNULL(PAT4.PAT_LIVING_STAT_C,0) = '1'			-- EXCLUDE PATIENTS LISTED AS DECEASED IN EPIC
AND		FYIF.PATIENT_ID IS NULL							-- EXCLUDE PATIENTS WHO HAVE OPTED OUT OF BEING CONTACTED FOR RESEARCH RECRUITME
AND		CP.COMMUNICATION_CONCEPT_ID = '28102'			-- Include patients who approved bulk communication as a communication concept.
AND		APRV.APRV_MEDIA_C = '2'							-- Include patients where MyChart is the approved communication media for a communication concept.
AND		PAT.EMAIL_ADDRESS IS NOT NULL					-- EMAIL ADDRESS MUST NOT BE NULL 
AND		PAT.EMAIL_ADDRESS LIKE '%@%.%'					-- EMAIL MUST BE IN PROPER FORMAT ABC@GMAIL.COM 
AND		ISNULL(PE.SERV_AREA_ID,11)=11
AND		(		ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1101%' --JHH
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1103%'--HCGH
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1105%'--Suburban
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1102%'--BVMC
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1104%'--Sibley
		)
AND		ISNULL(PAT.INTRPTR_NEEDED_YN,'N') <> 'Y'		--EXCLUDE interpreter=yes
--AND FLOOR(DATEDIFF(MM,PE.CONTACT_DATE,GETDATE())) <= 4	--Seen in last 4 months, to limit size of results (commented out for now as it may not be needed)

