--CCDA5937 Supplemental Code

--CCI
SELECT ID.IDENTITY_ID "EMRN"
   ,ROW_NUMBER() OVER (PARTITION BY RDI.NETWORKED_ID,RDM.METRICS_ID ORDER BY RDM.METRIC_LAST_UPD_TM DESC) AS Line,
   RDM.METRIC_STRING_VALUE AS [Index Score], RDM.METRIC_LAST_UPD_TM AS [Score Date]
FROM CLARITY.dbo.REG_DATA_METRICS RDM
INNER JOIN CLARITY.dbo.CL_CHRG_EDIT_RULE CCR ON CCR.RULE_ID = RDM.METRICS_ID
INNER JOIN CLARITY.dbo.REGISTRY_DATA_INFO RDI ON RDI.RECORD_ID = RDM.RECORD_ID
JOIN CLARITY..IDENTITY_ID ID ON RDI.NETWORKED_ID = ID.PAT_ID
INNER JOIN Analytics.dbo.CCDA5937_Demographics coh ON ID.IDENTITY_ID = coh.emrn
   AND ID.IDENTITY_TYPE_ID = 0
--AND RDI.RECORD_CREATION_DT BETWEEN COH.HOSP_ADM_DTTM AND COH.HOSP_DISCH_DTTM
WHERE RDM.METRICS_ID IN ('1500000001', '2101500001')
AND RDM.METRIC_LAST_UPD_TM >= '2022-01-01'

--Referrals 
SELECT coh.emrn, ref.ENTRY_DATE, refdx.DX_ID, edg.DX_NAME, icd10.CODE "icd10", icd9.CODE "icd9", ref.
   REFD_TO_DEPT_ID, dep.DEPARTMENT_NAME
FROM CLARITY.dbo.REFERRAL ref
INNER JOIN CLARITY..IDENTITY_ID ID ON ref.PAT_ID = ID.PAT_ID
INNER JOIN Analytics.dbo.CCDA5937_Demographics coh ON ID.IDENTITY_ID = coh.emrn
   AND ID.IDENTITY_TYPE_ID = 0
INNER JOIN CLARITY.dbo.REFERRAL_DX refdx ON ref.REFERRAL_ID = refdx.REFERRAL_ID
INNER JOIN clarity.dbo.clarity_dep dep ON ref.REFD_TO_DEPT_ID = dep.department_id
INNER JOIN CLARITY.dbo.EDG_CURRENT_ICD10 icd10 ON refdx.DX_ID = icd10.DX_ID
INNER JOIN CLARITY.dbo.EDG_CURRENT_ICD9 icd9 ON refdx.DX_ID = icd9.DX_ID
INNER JOIN CLARITY.dbo.CLARITY_EDG edg ON refdx.DX_ID = edg.DX_ID
WHERE dep.rpt_grp_ten = '1'
   AND dep.record_status IS NULL -- not disabled
   AND ref.ENTRY_DATE >='2022-01-01'
         --and (
         --icd10.CODE in ( select ICD10 from analytics.dbo.CCDA1226_icd10_outcome)
         --or icd9.CODE in ( select ICD9 from analytics.dbo.CCDA1226_icd9_outcome)
         --)
   AND ref.RFL_STATUS_C <> '4'
   AND ref.RFL_STATUS_C <> '5'

   --Investigation
   Identity_ID
   WHERE IDENTITY_ID = 'E101201990'
   --pat_id = 'Z1207753'
   ORDER_PROC
   WHERE pat_id = 'Z1207753'
   AND ORDERING_DATE BETWEEN '2023-01-10' AND '2023-01-12'
   --ORDER BY

   CLARITY_EAP
   WHERE PROC_ID = '121'

   ORDER_PROC
   WHERE ORDER_PROC_ID = '802970488'

   ZC_SPECIALTY_DEP
   WHERE SPECIALTY_DEP_C = 17