SELECT 
	a.*
	--,'Pat_'+ cast(ROW_NUMBER() OVER (ORDER BY A.IDENTITY_ID) as varchar) as 'Masked ID'
	,ROW_NUMBER() OVER (ORDER BY A.IDENTITY_ID) as 'PatientID'
	,checksum(NewId()) % 180 as'shifter'
FROM (
	SELECT DISTINCT
		II.IDENTITY_ID 
	FROM
		CLARITY..PATIENT PT
		INNER JOIN CLARITY..IDENTITY_ID II ON II.PAT_ID = PT.PAT_ID AND II.IDENTITY_TYPE_ID = 0
		INNER JOIN CLARITY..PAT_ENC_DX PEDX ON PEDX.PAT_ID = II.PAT_ID
		INNER JOIN CLARITY..PAT_ENC PE ON  PE.PAT_ENC_CSN_ID = PEDX.PAT_ENC_CSN_ID
		INNER JOIN CLARITY..CLARITY_DEP DEP ON DEP.DEPARTMENT_ID = PE.DEPARTMENT_ID
		INNER JOIN CLARITY..CLARITY_EDG EDG ON EDG.DX_ID = PEDX.DX_ID
		INNER JOIN CLARITY..EDG_CURRENT_ICD10 I10 ON I10.DX_ID = PEDX.DX_ID
		INNER JOIN CLARITY..EDG_CURRENT_ICD9 I9 ON I9.DX_ID = PEDX.DX_ID
	WHERE 
		PEDX.CONTACT_DATE BETWEEN '3/1/2016' AND '3/1/2018'
		AND PE.APPT_STATUS_C NOT IN (1,4,3,101)
 )A
