SELECT TOP 100 *
FROM CLARITY.dbo.PAT_ADDL_ADDR_DETAILS
WHERE ADDRESS_DETAILS_C in(6,7,8,9)
AND ADDRESS_DETAILS_VAL IS NOT NULL

--EPT 72
--AddressDim, PatientDim, CensusTractDim

SELECT ADDRESS_DETAILS_C, count(distinct pat_id) "pat_count"
FROM CLARITY.dbo.PAT_ADDL_ADDR_DETAILS
WHERE ADDRESS_DETAILS_VAL IS NOT NULL
GROUP BY ADDRESS_DETAILS_C
UNION
SELECT ADDRESS_DETAILS_C, count(distinct pat_id) "pat_count"
FROM CLARITY.dbo.PAT_ADDL_ADDR_DETAILS
--WHERE ADDRESS_DETAILS_VAL IS NOT NULL
GROUP BY ADDRESS_DETAILS_C

--7,641,952 vs 72,965