/****************************************************************************************
Author:			Guanyu
Date:			2022-03-14
JIRA:			[CCDA-3238]
Description:	Glycemic Effects of the COVID-19 Booster Vaccine in Type 1 Diabetes

Inclusion:		
1.	Age 18+
2.	ICD-10 (E10.*) – visit, billing, problem list, medical history
3.	Has received a dose of COVID vaccine
4.	Location: HCGH/Suburban/JHH/BVMC/Sibley
5.	Have active MyChart account




Exclusion:		

1.	Already received 3rd dose of COVID vaccine (booster)
2.	Patients known to be deceased in Epic.
3.	Patients who have opted out of being contacted for MyChart recruitment.  
4.	Patients who have opted out of being contacted for any reason. 




				
****************************************************************************************/
IF OBJECT_ID(N'TEMPDB..#inc_DX_LIST') IS NULL CREATE TABLE #inc_DX_LIST (DX_ID NUMERIC)
INSERT INTO #inc_DX_LIST (DX_ID)
SELECT DX_ID FROM CLARITY..EDG_CURRENT_ICD10 WHERE CODE LIKE 'E10.%'




IF OBJECT_ID(N'TEMPDB..#inc_dx') IS NOT NULL DROP TABLE #inc_dx
SELECT T.*
INTO #inc_dx
FROM 
		(
		SELECT PAT.PAT_ID--,ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE)  
		FROM PATIENT PAT
		INNER JOIN CLARITY.DBO.PAT_ENC PE ON PAT.PAT_ID = PE.PAT_ID
		INNER JOIN CLARITY.DBO.PAT_ENC_DX PED ON PE.PAT_ENC_CSN_ID = PED.PAT_ENC_CSN_ID
		INNER JOIN #inc_DX_LIST ED ON PED.DX_ID = ED.DX_ID		
		UNION 	
		--HSP_BILLING_DX
		SELECT DISTINCT PAT.PAT_ID--,ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE)  
		FROM PATIENT PAT
		INNER JOIN CLARITY.DBO.PAT_ENC PE ON PAT.PAT_ID = PE.PAT_ID
		INNER JOIN CLARITY.DBO.HSP_ACCT_DX_LIST DXL WITH (NOLOCK) ON PE.HSP_ACCOUNT_ID = DXL.HSP_ACCOUNT_ID
		INNER JOIN #inc_DX_LIST ED ON DXL.DX_ID = ED.DX_ID		
		UNION 
		--PROBLEM LIST
		SELECT DISTINCT PAT.PAT_ID
		FROM PATIENT PAT 
		INNER JOIN CLARITY.DBO.PROBLEM_LIST PL ON PAT.PAT_ID = PL.PAT_ID
		INNER JOIN #inc_DX_LIST ED ON PL.DX_ID = ED.DX_ID
		WHERE ISNULL(PL.PROBLEM_STATUS_C,0) IN(1) -- ACTIVE/RESOLVED
		UNION
		--HSP_ADMISSION_DX
		SELECT  DISTINCT PAT.PAT_ID
		FROM PATIENT PAT
		INNER JOIN HSP_ADMIT_DIAG HAD ON HAD.PAT_ID = PAT.PAT_ID
		INNER JOIN CLARITY..PAT_ENC PE ON PE.PAT_ENC_CSN_ID = HAD.PAT_ENC_CSN_ID
		INNER JOIN #inc_DX_LIST ED ON HAD.DX_ID = ED.DX_ID
		UNION
		--ARPB DX
		SELECT  DISTINCT PAT.PAT_ID
		FROM PATIENT PAT
		INNER JOIN ARPB_TRANSACTIONS AT ON AT.PATIENT_ID = PAT.PAT_ID
		INNER JOIN V_ARPB_CODING_DX ARPB ON ARPB.TX_ID = AT.TX_ID
		INNER JOIN #inc_DX_LIST ED ON ARPB.DX_ID = ED.DX_ID 
		) T


IF OBJECT_ID(N'TEMPDB..#INC_COV_VAC') IS NOT NULL DROP TABLE #INC_COV_VAC
SELECT DISTINCT PAT_ID
INTO #INC_COV_VAC
FROM 
	(SELECT P.PAT_ID 
	FROM PAT_IMMUNIZATIONS P
	INNER JOIN CLARITY..IMMUNE I ON P.IMMUNE_ID = I.IMMUNE_ID
	INNER JOIN CLARITY..CLARITY_IMMUNZATN CI ON CI.IMMUNZATN_ID = I.IMMUNZATN_ID
	WHERE CI.NAME LIKE '%COVID%'
	AND I.IMMNZTN_STATUS_C = 1) P

IF OBJECT_ID(N'TEMPDB..#EXCL_COV_BSTR') IS NOT NULL DROP TABLE #EXCL_COV_BSTR
SELECT DISTINCT PAT_ID
INTO #EXCL_COV_BSTR
FROM 
	(SELECT P.PAT_ID
	FROM PAT_IMMUNIZATIONS P
	INNER JOIN CLARITY..IMMUNE I ON P.IMMUNE_ID = I.IMMUNE_ID
	INNER JOIN CLARITY..CLARITY_IMMUNZATN CI ON CI.IMMUNZATN_ID = I.IMMUNZATN_ID
	WHERE CI.NAME LIKE '%COVID%'
	AND I.IMMNZTN_STATUS_C = 1
	GROUP BY P.PAT_ID
	HAVING COUNT(P.PAT_ID)>=3
	UNION
	SELECT P.PAT_ID
	FROM PAT_IMMUNIZATIONS P
	INNER JOIN CLARITY..IMMUNE I ON P.IMMUNE_ID = I.IMMUNE_ID
	INNER JOIN CLARITY..CLARITY_IMMUNZATN CI ON CI.IMMUNZATN_ID = I.IMMUNZATN_ID
	WHERE CI.IMMUNZATN_ID = 210279 --Mordena booster
	AND I.IMMNZTN_STATUS_C = 1) P

SELECT DISTINCT
PAT.PAT_ID	AS 'ID'
FROM
	PATIENT PAT
	INNER JOIN	CLARITY.dbo.PATIENT_4					pat4	on pat.pat_id = pat4.pat_id 
	INNER JOIN	CLARITY.dbo.PATIENT_MYC					mychart on mychart.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.MYC_PATIENT					myc		on myc.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.COMMUNICATION_PREFERENCES	cp		on cp.PREFERENCES_ID=pat4.PREFERENCES_ID
	INNER JOIN	CLARITY.dbo.COMM_PREFERENCES_APRV		aprv	on cp.PREFERENCES_ID=aprv.PREFERENCES_ID and cp.LINE=aprv.GROUP_LINE
		LEFT JOIN	CLARITY.dbo.PATIENT_FYI_FLAGS fyif	ON fyif.PATIENT_ID = pat.PAT_ID and fyif.PAT_FLAG_TYPE_C = '1092'
	INNER JOIN CLARITY..PAT_ENC PE ON PE.PAT_ID = PAT.PAT_ID
	INNER JOIN #INC_COV_VAC I ON I.PAT_ID = PAT.PAT_ID
	INNER JOIN #inc_dx DX ON DX.PAT_ID = PAT.PAT_ID
WHERE 
		FLOOR(DATEDIFF(DD,PAT.BIRTH_DATE,GETDATE())/365.25) >= 18
AND 	MYCHART.MYCHART_STATUS_C = '1'					-- PATIENTS WITH AN ACTIVE MYCHART ACCOUNT (DEFINED AS HAVING A LOG IN WITHIN THE LAST YEAR – BASED ON EXTRACT DATE)
AND		ISNULL(PAT4.PAT_LIVING_STAT_C,0) = '1'			-- EXCLUDE PATIENTS LISTED AS DECEASED IN EPIC
AND		FYIF.PATIENT_ID IS NULL							-- EXCLUDE PATIENTS WHO HAVE OPTED OUT OF BEING CONTACTED FOR RESEARCH RECRUITME
AND		CP.COMMUNICATION_CONCEPT_ID = '28102'
AND		APRV.APRV_MEDIA_C = '2'	
AND		PAT.EMAIL_ADDRESS IS NOT NULL					-- EMAIL ADDRESS MUST NOT BE NULL 
AND		PAT.EMAIL_ADDRESS LIKE '%@%.%'					-- EMAIL MUST BE IN PROPER FORMAT ABC@GMAIL.COM 
AND		ISNULL(PE.SERV_AREA_ID,11)=11
AND		(		ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1101%' --JHH
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1130%'--HCGH
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1105%'--Suburban
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1102%'--BVMC
			OR	ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1104%'
			)--Sibley)
AND		ISNULL(PAT.INTRPTR_NEEDED_YN,'N') <> 'Y'		--EXCLUDE interpreter=yes
AND		PAT.PAT_ID NOT IN (	
		SELECT PAT_ID FROM #EXCL_COV_BSTR )

