--Determining ICU Units in CLARITY
SELECT D1.DEPARTMENT_ID, DEPARTMENT_NAME, D2.ICU_DEPT_YN FROM
CLARITY..CLARITY_DEP D1
INNER JOIN CLARITY..CLARITY_DEP_2 D2 ON D1.DEPARTMENT_ID = D2.DEPARTMENT_ID
WHERE ISNULL(D2.ICU_DEPT_YN,'N') = 'Y'
 
union
 
SELECT DEPARTMENT_ID , DEPARTMENT_NAME,'Y' FROM CLARITY..CLARITY_DEP where DEPARTMENT_NAME LIKE '%ICU%' OR DEPARTMENT_NAME LIKE '%INTENSIVE%'
ORDER BY DEPARTMENT_NAME;