--SDOH in CLARITY (query populates EDW)
 SELECT 
SDD_ENTRIES.SDOH_DATA_ID SOCIALDETERMINANTDATAEPICID,
       SDD_DATA.PAT_ID AS PATIENTID,
       SDD_ENTRIES.CONTACT_DATE_REAL DETERMINANTDATE,
       SDD_ENTRIES.CONTACT_DATE CONTACTDATE,
       SDD_ENTRIES.LINE LINE,
     --  FlowsheetEncounter.PAT_ENC_CSN_ID ENCOUNTERID,
       CAST ( NULL AS varchar(50) ) DEPARTMENTID,
       CAST ( NULL AS varchar(50) ) PLACEOFSERVICEID,
      -- COALESCE( PAT_ENC_HSP.ADMISSION_PROV_ID, FlowsheetEncounter.VISIT_PROV_ID) PROVIDERID,
       Domain.NAME DOMAIN,
       SDD_ENTRIES.ENTRY_DOM_CONFIG_ID SOURCEID,
       ConcernLevel.NAME LEVELOFCONCERN,
	   	GP.DISP_NAME												'SDOH_question',
		IP_FLWSHT_MEAS.MEAS_VALUE											'SDOH_answer'
FROM 
	SDD_ENTRIES
    LEFT OUTER JOIN SDD_DATA ON SDD_DATA.SDOH_DATA_ID = SDD_ENTRIES.SDOH_DATA_ID
    LEFT OUTER JOIN IP_FLWSHT_REC ON SDD_ENTRIES.ENTRY_CALC_FSD_ID = IP_FLWSHT_REC.FSD_ID
    LEFT OUTER JOIN IP_FLWSHT_MEAS ON SDD_ENTRIES.ENTRY_CALC_FSD_ID = IP_FLWSHT_MEAS.FSD_ID AND SDD_ENTRIES.ENTRY_CALC_FSD_LINE = IP_FLWSHT_MEAS.LINE
	LEFT OUTER JOIN ZC_SDOH_ADDRESSED Domain ON Domain.SDOH_ADDRESSED_C = SDD_DATA.DOMAIN_C
	LEFT OUTER JOIN ZC_FIN_RESOURCE_RISK ConcernLevel ON ConcernLevel.FIN_RESOURCE_RISK_C = SDD_ENTRIES.ENTRY_CONCERN_LVL_C
	LEFT JOIN dbo.IP_FLO_GP_DATA gp WITH (NOLOCK) on gp.FLO_MEAS_ID = IP_FLWSHT_MEAS.FLO_MEAS_ID
WHERE	SDD_ENTRIES.ENTRY_CALC_FSD_ID IS NOT NULL 
    AND SDD_ENTRIES.ENTRY_CALC_FSD_LINE IS NOT NULL
    AND COALESCE ( SDD_DATA.RECORD_STATUS_C, 1 ) NOT IN ( 2, 6 )
UNION
SELECT 
SDD_ENTRIES.SDOH_DATA_ID SOCIALDETERMINANTDATAEPICID,
       SDD_DATA.PAT_ID AS PATIENTID,
       SDD_ENTRIES.CONTACT_DATE_REAL DETERMINANTDATE,
       SDD_ENTRIES.CONTACT_DATE CONTACTDATE,
       SDD_ENTRIES.LINE LINE,
     --  FlowsheetEncounter.PAT_ENC_CSN_ID ENCOUNTERID,
       CAST ( NULL AS varchar(50) ) DEPARTMENTID,
       CAST ( NULL AS varchar(50) ) PLACEOFSERVICEID,
      -- COALESCE( PAT_ENC_HSP.ADMISSION_PROV_ID, FlowsheetEncounter.VISIT_PROV_ID) PROVIDERID,
       Domain.NAME DOMAIN,
       SDD_ENTRIES.ENTRY_DOM_CONFIG_ID SOURCEID,
       ConcernLevel.NAME LEVELOFCONCERN,
	   	GP.DISP_NAME												'SDOH_question',
		IP_FLWSHT_MEAS.MEAS_VALUE											'SDOH_answer'
	   FROM 
SDD_ENTRIES
    LEFT OUTER JOIN SDD_DATA ON SDD_DATA.SDOH_DATA_ID = SDD_ENTRIES.SDOH_DATA_ID
    LEFT OUTER JOIN PAT_ENC Encounter ON Encounter.PAT_ENC_CSN_ID = SDD_ENTRIES.ENTRY_PAT_ENC_CSN_ID
    LEFT OUTER JOIN SDOH_DOM_CONFIG_INFO ON SDOH_DOM_CONFIG_INFO.DOM_CONFIG_ID = SDD_ENTRIES.ENTRY_DOM_CONFIG_ID
    LEFT OUTER JOIN CL_CHRG_EDIT_RULE ON SDOH_DOM_CONFIG_INFO.SOURCE_RULE_ID = CL_CHRG_EDIT_RULE.RULE_ID
    LEFT OUTER JOIN ALL_CATEGORIES ON ALL_CATEGORIES.INI = CL_CHRG_EDIT_RULE.NETWORKED_INI
									AND ALL_CATEGORIES.ITEM = CL_CHRG_EDIT_RULE.NETWORKED_ITEM
									AND SDD_ENTRIES.ENTRY_INTERPRETATION = ALL_CATEGORIES.VALUE_C
    LEFT OUTER JOIN ZC_SDOH_ADDRESSED Domain ON Domain.SDOH_ADDRESSED_C = SDD_DATA.DOMAIN_C
    LEFT OUTER JOIN ZC_FIN_RESOURCE_RISK ConcernLevel ON ConcernLevel.FIN_RESOURCE_RISK_C = SDD_ENTRIES.ENTRY_CONCERN_LVL_C
	LEFT OUTER JOIN IP_FLWSHT_REC ON SDD_ENTRIES.ENTRY_CALC_FSD_ID = IP_FLWSHT_REC.FSD_ID
    LEFT OUTER JOIN IP_FLWSHT_MEAS ON SDD_ENTRIES.ENTRY_CALC_FSD_ID = IP_FLWSHT_MEAS.FSD_ID AND SDD_ENTRIES.ENTRY_CALC_FSD_LINE = IP_FLWSHT_MEAS.LINE
	LEFT JOIN IP_FLO_GP_DATA gp WITH (NOLOCK) on gp.FLO_MEAS_ID = IP_FLWSHT_MEAS.FLO_MEAS_ID
WHERE
	SDD_ENTRIES.ENTRY_CALC_FSD_ID IS NULL
    AND SDD_ENTRIES.ENTRY_CALC_FSD_LINE IS NULL
    AND COALESCE ( SDD_DATA.RECORD_STATUS_C, 1 ) NOT IN ( 2, 6 )
ORDER BY SDD_ENTRIES.CONTACT_DATE DESC;