/****************************************************************************************
Author:			mcook49
Date:			2022-02-24
JIRA:			[CCDA-4041]
Description:	Autosomal Dominant Hypocalcemia Types 1 and 2 (ADH1/2) Disease Monitoring Study (DMS)

Inclusion:		
1.	Age: Birth to 90
2.	Location: All JH location except ACH.
3.	Patients with a diagnosis of 1) E20.8 (other hypoparathyroidism) or 2) E20.9 (hypoparathyroidism unspecified) or 3) diagnosis name contains term ‘hypoparathyroidism’. Look for diagnosis in encounter diagnosis (from 2013), billing diagnosis (from 2013) and problem list (active).
4.	Have active MyChart account



Exclusion:																													
																															
1.	Patients known to be deceased in Epic.
2.	Patients who have opted out of being contacted for MyChart recruitment.  
3.	Patients who have opted out of being contacted for any reason. 
				
****************************************************************************************/
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;

--Primary Aldosteronism
IF OBJECT_ID(N'TEMPDB..#inc_dx') IS NULL CREATE TABLE #inc_dx (DX_ID NUMERIC)
INSERT INTO #inc_dx (DX_ID)
SELECT DX_ID FROM CLARITY..EDG_CURRENT_ICD10 
WHERE CODE LIKE 'E20.8'
   OR CODE LIKE 'E20.9'
UNION
SELECT DX_ID FROM CLARITY..CLARITY_EDG
WHERE DX_NAME like '%hypoparathyroidism%'

--Get included patients
IF OBJECT_ID(N'TEMPDB..#inc') IS NOT NULL DROP TABLE #inc
SELECT DISTINCT DX.*
INTO #inc
FROM 
		(
		SELECT DISTINCT PL.PAT_ID 
		FROM CLARITY..PROBLEM_LIST PL
		JOIN CLARITY..CLARITY_EDG EDG ON EDG.DX_ID=PL.DX_ID
		INNER JOIN #inc_dx I ON I.DX_ID = PL.DX_ID
		WHERE ISNULL(PL.PROBLEM_STATUS_C,0) IN(0,1) -- ACTIVE
		--AND PL.NOTED_DATE >= '2013-01-01' --From 01 January 2013
		UNION
		SELECT DISTINCT PAT.PAT_ID --,ISNULL(ENC.EFFECTIVE_DATE_DTTM,ENC.CONTACT_DATE)
		FROM CLARITY..PATIENT PAT 
		JOIN CLARITY..PAT_ENC ENC ON ENC.PAT_ID=PAT.PAT_ID
		JOIN CLARITY..PAT_ENC_DX DX ON DX.PAT_ENC_CSN_ID=ENC.PAT_ENC_CSN_ID
		JOIN CLARITY..CLARITY_EDG EDG ON EDG.DX_ID=DX.DX_ID
		INNER JOIN #inc_dx I ON I.DX_ID = DX.DX_ID
		WHERE DX.CONTACT_DATE >= '2013-01-01' --From 01 January 2013
		UNION
		SELECT DISTINCT PAT.PAT_ID
		FROM        
		CLARITY..PATIENT PAT 
		JOIN CLARITY..PAT_ENC ENC ON ENC.PAT_ID=PAT.PAT_ID
		JOIN CLARITY..ARPB_TRANSACTIONS ARPB ON ARPB.PATIENT_ID=PAT.PAT_ID
		JOIN CLARITY..CLARITY_EDG EDG ON EDG.DX_ID=ARPB.PRIMARY_DX_ID 
		INNER JOIN #inc_dx I ON I.DX_ID = EDG.DX_ID
		WHERE ARPB.SERVICE_DATE >= '2013-01-01' --From 01 January 2013
		UNION
		SELECT DISTINCT PAT.PAT_ID  
		FROM CLARITY..PATIENT PAT
		INNER JOIN CLARITY..PAT_ENC PE ON PAT.PAT_ID = PE.PAT_ID
		INNER JOIN CLARITY..HSP_ACCT_DX_LIST DXL  ON PE.HSP_ACCOUNT_ID = DXL.HSP_ACCOUNT_ID	
		INNER JOIN CLARITY..CLARITY_EDG EDG ON EDG.DX_ID = DXL.DX_ID
		INNER JOIN #inc_dx I ON I.DX_ID = EDG.DX_ID
		WHERE PE.CONTACT_DATE >= '2013-01-01' --From 01 January 2013
		) DX
		INNER JOIN CLARITY..PATIENT P ON P.PAT_ID = DX.PAT_ID
		INNER JOIN CLARITY..PAT_ENC PE ON PE.PAT_ID = DX.PAT_ID
		INNER JOIN CLARITY..CLARITY_DEP DEP ON DEP.DEPARTMENT_ID = ISNULL(PE.EFFECTIVE_DEPT_ID,PE.DEPARTMENT_ID)
WHERE
		ISNULL(DEP.SERV_AREA_ID,11)=11
		AND DEP.DEPARTMENT_ID NOT LIKE '1108%' --Not ACH
		AND ISNULL(PE.APPT_STATUS_C,2) = 2 
		AND FLOOR(DATEDIFF(DD,P.BIRTH_DATE,GETDATE())/365.25) <= 90 --Birth to 90 years old

SELECT DISTINCT
PAT.PAT_ID	AS 'ID'
FROM
	CLARITY.DBO.PATIENT PAT
	INNER JOIN CLARITY..IDENTITY_ID II ON II.PAT_ID = PAT.PAT_ID AND II.IDENTITY_TYPE_ID = 0
	INNER JOIN	CLARITY.dbo.PATIENT_4					pat4	on pat.pat_id = pat4.pat_id 
	INNER JOIN	CLARITY.dbo.PATIENT_MYC					mychart on mychart.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.MYC_PATIENT					myc		on myc.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.COMMUNICATION_PREFERENCES	cp		on cp.PREFERENCES_ID=pat4.PREFERENCES_ID
	INNER JOIN	CLARITY.dbo.COMM_PREFERENCES_APRV		aprv	on cp.PREFERENCES_ID=aprv.PREFERENCES_ID and cp.LINE=aprv.GROUP_LINE
		LEFT JOIN	CLARITY.dbo.PATIENT_FYI_FLAGS fyif	ON fyif.PATIENT_ID = pat.PAT_ID and fyif.PAT_FLAG_TYPE_C = '1092'
	INNER JOIN #inc DX ON DX.PAT_ID = PAT.PAT_ID
WHERE 
	 	MYCHART.MYCHART_STATUS_C = '1'					-- PATIENTS WITH AN ACTIVE MYCHART ACCOUNT (DEFINED AS HAVING A LOG IN WITHIN THE LAST YEAR – BASED ON EXTRACT DATE)
AND		ISNULL(PAT4.PAT_LIVING_STAT_C,0) = '1'			-- EXCLUDE PATIENTS LISTED AS DECEASED IN EPIC
AND		FYIF.PATIENT_ID IS NULL							-- EXCLUDE PATIENTS WHO HAVE OPTED OUT OF BEING CONTACTED FOR RESEARCH RECRUITME
AND		CP.COMMUNICATION_CONCEPT_ID = '28102'
AND		APRV.APRV_MEDIA_C = '2'	
AND		PAT.EMAIL_ADDRESS IS NOT NULL					-- EMAIL ADDRESS MUST NOT BE NULL 
AND		PAT.EMAIL_ADDRESS LIKE '%@%.%'					-- EMAIL MUST BE IN PROPER FORMAT ABC@GMAIL.COM 
