/****************************************************************************************
Author:			mcook49
Date:			2022-03-29
JIRA:			[CCDA-3179]
Description:	Living with heart failure and multimorbidity

Inclusion:		
1.	Age: 50 years and older as of the date query runs.
2.	Location: JHH
3.	Having heart failure (ICD 10 - I50.9) AND one other chronic disease from the list (diagnosis codes are attached separately)
4.	Have active MyChart account





Exclusion:		

1.	Patients known to be deceased in Epic.
2.	Patients who have opted out of being contacted for MyChart recruitment.  
3.	Patients who have opted out of being contacted for any reason. 




				
****************************************************************************************/
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;

--Heart Disease
IF OBJECT_ID(N'TEMPDB..#inc_DX_LIST') IS NULL CREATE TABLE #inc_DX_LIST (DX_ID NUMERIC)
INSERT INTO #inc_DX_LIST (DX_ID)
SELECT DX_ID FROM CLARITY..EDG_CURRENT_ICD10 WHERE CODE LIKE 'I50.9'

--Other ICD's of interest
IF OBJECT_ID(N'TEMPDB..#inc_DX_LIST_2') IS NULL
   CREATE TABLE #inc_DX_LIST_2 (DX_ID NUMERIC);
INSERT INTO #inc_DX_LIST_2 (DX_ID)
SELECT DX_ID
FROM CLARITY..EDG_CURRENT_ICD10
WHERE CODE IN (
      'B20', 'J45', 'G30.9', 'I48.20', 'M54.5', 'M54.3', 'C80.1', 'C79.9', 'I67.9', 'I69.959', 'E78', 'N18.9', 
      'I73.9', 'K63.9', 'J44.9', 'F32', 'E08.9', 'E11.69', 'H91.90', 'I51.9', 'I10', 'I24.9', 'C95.90', 
      'C85.90', 'C79.9', 'K76.9', 'N18.3', 'M19.90', 'M81', 'E66', 'K27.9', 'I73.9', 'I09.9', 'M06.9', 'M79', 
      'K92.9', 'I63.9', 'E07.9', 'I53.1'
      )

--Inner join on heart first, then see what ID's also have at least one other dx
IF OBJECT_ID(N'TEMPDB..#inc_dx') IS NOT NULL DROP TABLE #inc_dx
SELECT T.*
INTO #inc_dx
FROM 
		(
		SELECT PAT.PAT_ID--,ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE)  
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.PAT_ENC PE ON PAT.PAT_ID = PE.PAT_ID
		INNER JOIN CLARITY.DBO.PAT_ENC_DX PED ON PE.PAT_ENC_CSN_ID = PED.PAT_ENC_CSN_ID
		INNER JOIN #inc_DX_LIST ED ON PED.DX_ID = ED.DX_ID
		INNER JOIN (select PAT_ID from CLARITY.DBO.PAT_ENC_DX PED2 JOIN #inc_DX_LIST_2 DX2 ON DX2.DX_ID = PED2.DX_ID) ED2 on PAT.PAT_ID = ED2.PAT_ID
		UNION 	
		--HSP_BILLING_DX
		SELECT PAT.PAT_ID--,ISNULL(PE.EFFECTIVE_DATE_DT,PE.CONTACT_DATE)  
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.PAT_ENC PE ON PAT.PAT_ID = PE.PAT_ID
		INNER JOIN CLARITY.DBO.HSP_ACCT_DX_LIST DXL WITH (NOLOCK) ON PE.HSP_ACCOUNT_ID = DXL.HSP_ACCOUNT_ID
		INNER JOIN #inc_DX_LIST ED ON DXL.DX_ID = ED.DX_ID
		INNER JOIN (select HSP_ACCOUNT_ID from CLARITY.DBO.HSP_ACCT_DX_LIST DXL JOIN #inc_DX_LIST_2 DX2 ON DX2.DX_ID = DXL.DX_ID) ED2 ON DXL.HSP_ACCOUNT_ID = ED2.HSP_ACCOUNT_ID
		UNION 
		--PROBLEM LIST
		SELECT DISTINCT PAT.PAT_ID
		FROM CLARITY.DBO.PATIENT PAT 
		INNER JOIN CLARITY.DBO.PROBLEM_LIST PL ON PAT.PAT_ID = PL.PAT_ID
		INNER JOIN #inc_DX_LIST ED ON PL.DX_ID = ED.DX_ID
		INNER JOIN (select PAT_ID from CLARITY.DBO.PROBLEM_LIST PL2 JOIN #inc_DX_LIST_2 DX2 ON DX2.DX_ID = PL2.DX_ID WHERE ISNULL(PL2.PROBLEM_STATUS_C,0) IN(1)) ED2 on PAT.PAT_ID = ED2.PAT_ID
		WHERE ISNULL(PL.PROBLEM_STATUS_C,0) IN(1) -- ACTIVE/RESOLVED
		UNION
		--HSP_ADMISSION_DX
		SELECT  DISTINCT PAT.PAT_ID
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.HSP_ADMIT_DIAG HAD ON HAD.PAT_ID = PAT.PAT_ID
		INNER JOIN CLARITY..PAT_ENC PE ON PE.PAT_ENC_CSN_ID = HAD.PAT_ENC_CSN_ID
		INNER JOIN #inc_DX_LIST ED ON HAD.DX_ID = ED.DX_ID
		INNER JOIN (select PAT_ID from CLARITY.DBO.HSP_ADMIT_DIAG HAD2 JOIN #inc_DX_LIST_2 DX2 ON DX2.DX_ID = HAD2.DX_ID) ED2 on PAT.PAT_ID = ED2.PAT_ID
		UNION
		--ARPB DX
		SELECT  DISTINCT PAT.PAT_ID
		FROM CLARITY.DBO.PATIENT PAT
		INNER JOIN CLARITY.DBO.ARPB_TRANSACTIONS AT ON AT.PATIENT_ID = PAT.PAT_ID
		INNER JOIN CLARITY.DBO.V_ARPB_CODING_DX ARPB ON ARPB.TX_ID = AT.TX_ID
		INNER JOIN #inc_DX_LIST ED ON ARPB.DX_ID = ED.DX_ID 
		INNER JOIN (select TX_ID from CLARITY.DBO.V_ARPB_CODING_DX ARPB2 JOIN #inc_DX_LIST_2 DX2 ON DX2.DX_ID = ARPB2.DX_ID) ED2 on AT.TX_ID = ED2.TX_ID
		) T

SELECT DISTINCT
PAT.PAT_ID	AS 'ID'
FROM
	CLARITY.DBO.PATIENT PAT
	INNER JOIN	CLARITY.dbo.PATIENT_4					pat4	on pat.pat_id = pat4.pat_id 
	INNER JOIN	CLARITY.dbo.PATIENT_MYC					mychart on mychart.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.MYC_PATIENT					myc		on myc.pat_id = pat.pat_id
	INNER JOIN	CLARITY.dbo.COMMUNICATION_PREFERENCES	cp		on cp.PREFERENCES_ID=pat4.PREFERENCES_ID
	INNER JOIN	CLARITY.dbo.COMM_PREFERENCES_APRV		aprv	on cp.PREFERENCES_ID=aprv.PREFERENCES_ID and cp.LINE=aprv.GROUP_LINE
		LEFT JOIN	CLARITY.dbo.PATIENT_FYI_FLAGS fyif	ON fyif.PATIENT_ID = pat.PAT_ID and fyif.PAT_FLAG_TYPE_C = '1092'
	INNER JOIN CLARITY..PAT_ENC PE ON PE.PAT_ID = PAT.PAT_ID
	INNER JOIN #inc_dx DX ON DX.PAT_ID = PAT.PAT_ID
WHERE 
		FLOOR(DATEDIFF(DD,PAT.BIRTH_DATE,GETDATE())/365.25) >= 50 -- 50 Years or older when query runs
AND 	MYCHART.MYCHART_STATUS_C = '1'					-- PATIENTS WITH AN ACTIVE MYCHART ACCOUNT (DEFINED AS HAVING A LOG IN WITHIN THE LAST YEAR – BASED ON EXTRACT DATE)
AND		ISNULL(PAT4.PAT_LIVING_STAT_C,0) = '1'			-- EXCLUDE PATIENTS LISTED AS DECEASED IN EPIC
AND		FYIF.PATIENT_ID IS NULL							-- EXCLUDE PATIENTS WHO HAVE OPTED OUT OF BEING CONTACTED FOR RESEARCH RECRUITME
AND		CP.COMMUNICATION_CONCEPT_ID = '28102'			-- Include patients who approved bulk communication as a communication concept.
AND		APRV.APRV_MEDIA_C = '2'							-- Include patients where MyChart is the approved communication media for a communication concept.
AND		PAT.EMAIL_ADDRESS IS NOT NULL					-- EMAIL ADDRESS MUST NOT BE NULL 
AND		PAT.EMAIL_ADDRESS LIKE '%@%.%'					-- EMAIL MUST BE IN PROPER FORMAT ABC@GMAIL.COM 
AND		ISNULL(PE.SERV_AREA_ID,11)=11
AND		(		ISNULL(PE.EFFECTIVE_DEPT_ID,DEPARTMENT_ID) LIKE '1101%' --JHH
		)
AND FLOOR(DATEDIFF(MM,PE.CONTACT_DATE,GETDATE())) <= 4	--Seen in last 4 months, to limit size of results

