ALTER proc dbo.[CCDA2715_Sharp_Sarcoidosis_Encounters_sp] AS
/**********************************************************************************
Author:  Michael Cook
Date: 7/8/2021
JIRA: CCDA-2715
Description: A one-time extract of Adult patients residing in MD seen at the Johns Hopkins Sarcoidosis Clinic. 
This proc creates the Encounters table.
Example:
    EXEC dbo.[CCDA2715_Sharp_Sarcoidosis_Encounters_sp]
     
Revision History:
Date            Author          JIRA            Comment
[date]      [your name]     CCDA-xxx            [Comments about what was changed and why]
***********************************************************************************/

SET NOCOUNT ON;

drop table if exists Analytics.dbo.CCDA2715_Sharp_Encounters;


WITH COH AS (
SELECT DISTINCT PAT_ID
FROM CLARITY..PAT_LIST
where LIST_ID = '630939'
),

ENC AS (
SELECT *
FROM CLARITY..PAT_ENC
WHERE ENC_TYPE_C IN ( '1000', '1001', '1003', '1004', '101', '108', '1199', 
'1200', '1201', '121', '1214', '2', '200', '210', '2100', '2101',
'2501', '2502', '2508', '2520', '2521', '2522', '2525', '2526', '2529',
'2531', '50', '62', '76', '81', '91', '20', '55')
AND EFFECTIVE_DATE_DTTM >= '2017-01-01'
),

HT AS
(
	SELECT A.*,ROW_NUMBER()OVER (partition BY PAT_ID,PAT_ENC_CSN_ID ORDER BY DD) AS RN
	FROM (SELECT DISTINCT
			S.PAT_ID
			,pe.PAT_ENC_CSN_ID
			,IP_FLWSHT_MEAS.MEAS_VALUE
			,flwgp.DISP_NAME
			,IP_FLWSHT_MEAS.recorded_time
			,flwgp.flo_MEAS_id
			,ABS(DATEDIFF(MINUTE,IP_FLWSHT_MEAS.recorded_time,pe.EFFECTIVE_DATE_DTTM)) AS DD
		FROM 
			COH S
			INNER JOIN ENC pe ON PE.PAT_ID = S.PAT_ID
			INNER JOIN CLARITY.dbo.IP_FLWSHT_REC IP_FLWSHT_REC  ON PE.INPATIENT_DATA_ID=IP_FLWSHT_REC.INPATIENT_DATA_ID
			INNER JOIN CLARITY.dbo.IP_FLWSHT_MEAS IP_FLWSHT_MEAS  ON IP_FLWSHT_REC.FSD_ID=IP_FLWSHT_MEAS.FSD_ID
			inner join clarity.dbo.IP_FLO_GP_DATA flwgp on flwgp.FLO_MEAS_ID=IP_FLWSHT_MEAS.FLO_MEAS_ID
			INNER JOIN CLARITY.DBO.IP_FLT_DATA TMP ON TMP.TEMPLATE_ID = IP_FLWSHT_MEAS.FLT_ID
		WHERE  
		IP_FLWSHT_MEAS.FLO_MEAS_ID IS NOT NULL
		AND flwgp.flo_MEAS_id IN (
								 '11') ) A	
),

WT AS
(
	SELECT A.*,ROW_NUMBER()OVER (partition BY PAT_ID,PAT_ENC_CSN_ID ORDER BY DD) AS RN
	FROM (SELECT DISTINCT
			S.PAT_ID
			,pe.PAT_ENC_CSN_ID
			,IP_FLWSHT_MEAS.MEAS_VALUE
			,flwgp.DISP_NAME
			,IP_FLWSHT_MEAS.recorded_time
			,flwgp.flo_MEAS_id
			,ABS(DATEDIFF(MINUTE,IP_FLWSHT_MEAS.recorded_time,pe.EFFECTIVE_DATE_DTTM)) AS DD
		FROM 
			COH S
			INNER JOIN ENC pe ON PE.PAT_ID = S.PAT_ID
			INNER JOIN CLARITY.dbo.IP_FLWSHT_REC IP_FLWSHT_REC  ON PE.INPATIENT_DATA_ID=IP_FLWSHT_REC.INPATIENT_DATA_ID
			INNER JOIN CLARITY.dbo.IP_FLWSHT_MEAS IP_FLWSHT_MEAS  ON IP_FLWSHT_REC.FSD_ID=IP_FLWSHT_MEAS.FSD_ID
			inner join clarity.dbo.IP_FLO_GP_DATA flwgp on flwgp.FLO_MEAS_ID=IP_FLWSHT_MEAS.FLO_MEAS_ID
			INNER JOIN CLARITY.DBO.IP_FLT_DATA TMP ON TMP.TEMPLATE_ID = IP_FLWSHT_MEAS.FLT_ID
		WHERE  
		IP_FLWSHT_MEAS.FLO_MEAS_ID IS NOT NULL
		AND flwgp.flo_MEAS_id IN (
								 '14') ) A	
),

BMI AS
(
	SELECT A.*,ROW_NUMBER()OVER (partition BY PAT_ID,PAT_ENC_CSN_ID ORDER BY DD) AS RN
	FROM (SELECT DISTINCT
			S.PAT_ID
			,pe.PAT_ENC_CSN_ID
			,IP_FLWSHT_MEAS.MEAS_VALUE
			,flwgp.DISP_NAME
			,IP_FLWSHT_MEAS.recorded_time
			,flwgp.flo_MEAS_id
			,ABS(DATEDIFF(MINUTE,IP_FLWSHT_MEAS.recorded_time,pe.EFFECTIVE_DATE_DTTM)) AS DD
		FROM 
			COH S
			INNER JOIN ENC pe ON PE.PAT_ID = S.PAT_ID
			INNER JOIN CLARITY.dbo.IP_FLWSHT_REC IP_FLWSHT_REC  ON PE.INPATIENT_DATA_ID=IP_FLWSHT_REC.INPATIENT_DATA_ID
			INNER JOIN CLARITY.dbo.IP_FLWSHT_MEAS IP_FLWSHT_MEAS  ON IP_FLWSHT_REC.FSD_ID=IP_FLWSHT_MEAS.FSD_ID
			inner join clarity.dbo.IP_FLO_GP_DATA flwgp on flwgp.FLO_MEAS_ID=IP_FLWSHT_MEAS.FLO_MEAS_ID
			INNER JOIN CLARITY.DBO.IP_FLT_DATA TMP ON TMP.TEMPLATE_ID = IP_FLWSHT_MEAS.FLT_ID
		WHERE  
		IP_FLWSHT_MEAS.FLO_MEAS_ID IS NOT NULL
		AND flwgp.flo_MEAS_id IN (
								 '301070') ) A	
)

Select DISTINCT II.IDENTITY_ID "EMRN", enc.PAT_ENC_CSN_ID, enc.EFFECTIVE_DATE_DTTM "Encounter_Date",
ze.[NAME] "Encounter_Type", dep.DEPARTMENT_NAME, dep.SPECIALTY "Dep_Specialty", occ.HX_OCCUPN "Pat_Occupation",
HT.MEAS_VALUE "Height_In_Inches", WT.MEAS_VALUE "Weight_In_Ounces", BMI.MEAS_VALUE "BMI"
--,val.FLO_MEAS_ID, val.MEAS_VALUE
--CASE WHEN val.FLO_MEAS_ID = '14' AND val.MEAS_VALUE is NOT NULL THEN val.MEAS_VALUE END AS "Weight",
--CASE WHEN val.FLO_MEAS_ID = '11' AND val.MEAS_VALUE is NOT NULL THEN val.MEAS_VALUE END AS "Height",
--CASE WHEN val.FLO_MEAS_ID = '301070' AND val.MEAS_VALUE is NOT NULL THEN val.MEAS_VALUE END AS "BMI"
--INTO Analytics.dbo.CCDA2715_Sharp_Encounters
FROM Clarity..PATIENT PT
INNER JOIN COH ON COH.PAT_ID = Pt.PAT_ID
INNER JOIN CLARITY..IDENTITY_ID II ON II.PAT_ID = PT.PAT_ID and II.IDENTITY_TYPE_ID = 0
INNER JOIN ENC enc on COH.PAT_ID = enc.PAT_ID
--INNER JOIN CLARITY..IP_FLWSHT_REC flo on ENC.INPATIENT_DATA_ID = flo.INPATIENT_DATA_ID
--INNER JOIN MEAS val on flo.FSD_ID = val.FSD_ID
INNER JOIN HT ON ENC.PAT_ENC_CSN_ID = HT.PAT_ENC_CSN_ID AND HT.RN = 1
INNER JOIN WT ON ENC.PAT_ENC_CSN_ID = WT.PAT_ENC_CSN_ID AND WT.RN = 1
INNER JOIN BMI ON ENC.PAT_ENC_CSN_ID = BMI.PAT_ENC_CSN_ID AND BMI.RN = 1
LEFT JOIN CLARITY..ZC_DISP_ENC_TYPE ze on enc.ENC_TYPE_C = ze.DISP_ENC_TYPE_C
LEFT JOIN CLARITY..CLARITY_DEP dep on enc.EFFECTIVE_DEPT_ID = dep.DEPARTMENT_ID
--LEFT JOIN CLARITY..PAT_OCCUPN_HX occ on enc.PAT_ENC_CSN_ID = occ.PAT_ENC_CSN_ID
LEFT JOIN CLARITY..PAT_OCCUPN_HX occ on coh.PAT_ID = occ.PAT_ID AND occ.LINE = 1
WHERE 1 = 1
--AND occ.HX_OCCUPN is not NULL
ORDER BY II.IDENTITY_ID, enc.EFFECTIVE_DATE_DTTM;

--FLO MEAS ID 11, 14, 301070


ALTER TABLE [Analytics].[dbo].[CCDA2715_Sharp_Encounters] REBUILD PARTITION = ALL  WITH (DATA_COMPRESSION = Page)